### ISSUE TITLE
`_` pattern

### ISSUE THREAD

**Issue by liquidev** [mica-lang/mica#148]
There should be a pattern that just discards whatever is matched against it:
```
let _ = 1
print(_)  # error
```
Right now this code compiles and runs, since `_` is a valid variable name.

**Comment by tony-go** [comment]
Hey @liquidev 👋🏼 

Is this [function](https://github.com/mica-lang/mica/blob/main/src/ll/parser.rs#L137) a good entry point to discard this identifier? (`_`)

**Comment by liquidev** [comment]
@tony-go Happy to see someone willing to help!

If you want to reserve an identifier, the best way to do that would be to introduce a keyword in the lexer - that's here:
https://github.com/mica-lang/mica/blob/260ce8958a628a1a088128414fe9b251c3ff10d6/src/ll/lexer.rs#L426-L430

Then introduce an AST node to represent the `_` token within the syntax tree:
https://github.com/mica-lang/mica/blob/260ce8958a628a1a088128414fe9b251c3ff10d6/src/ll/lexer.rs#L426-L430

And then you can move onto parsing it. It should simply be a matter of adding a new `match` arm in `Parser::parse_prefix`. You can look at how `nil`, `true`, and `false` are implemented as an example.

The next points of interest will be `CodeGenerator::generate_node`, where you'll want to emit an error whenever `_` is hit - since it is not a valid expression - and `CodeGenerator::generate_pattern_destructuring`, which is what handles all destructuring patterns.

Hope that helps!

**Comment by tony-go** [comment]
Hey @liquidev 👋🏼 

Thanks for this detailed answer 🙌🏼 

I didn't manage to attack it at the moment, but I'll keep it in my github notification ^^

Can't wait to give it a try :)

**Comment by grisenti** [comment]
Hi @liquidev, I got this feature working. Should I make a PR? Are you still interested in the project?

**Comment by liquidev** [comment]
@grisenti I'd be happy to review your code and merge it into `main` :grin:  

As for the question of whether I'm still interested in the project... This would probably deserve some more visible status update in the README, but over the past half year or so I've been kind of dissatisfied with my original design direction and have been thinking up a totally new language with not too dissimilar goals. Therefore I'm probably not going to focus on Mica any longer.

I'll be happy to do some passive maintainership in the meantime, but it's unlikely I'll work on adding any new features myself. Especially now that my time is spread thin between work and a different personal project ([stitchkit](https://github.com/abyteintime/stitchkit).)

**Comment by grisenti** [comment]
I understand. 

I'm not really a user of the language, I was just trying to understand your implementation to steal some good ideas for my own project. I like how you structured the AST and how you did error handling, I think they are both better than what I ended up with. Also, very good documentation.

I'll keep an eye out for that new language if you end up making it.
